### ISSUE TITLE
Automatic exchange of AcessToken between Netbanking SDK and Core SDK does not work

### ISSUE THREAD

**Issue by Vratislav** [Ceskasporitelna/cs-netbanking-sdk-droid#19]
When going step by step according to https://github.com/Ceskasporitelna/cs-netbanking-sdk-droid/blob/master/docs/netbanking.md#with-locker-preffered-method . The calls Netbanking ends in 403.

When using the without locker option, it does work and returns 200
https://github.com/Ceskasporitelna/cs-netbanking-sdk-droid/blob/master/docs/netbanking.md#without-locker

**Comment by hauseja3** [comment]
Hi @Vratislav, thanks for your point. It will be fixed in new version. Thank you for staying in touch! 🎉
